### ISSUE TITLE
Doesnt build on OpenBSD

### ISSUE THREAD

**Issue by landryb** [ogham/rust-users#12]
Wanted to try exa on OpenBSD, but the users crate obviously fails to build:

```
[14:58] c64:/tmp/rust-users/ $cargo build                          
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.21                                                                                                                     Compiling users v0.5.2 (file:///tmp/rust-users)              
error[E0412]: type name `c_char` is undefined or not in scope
  --> src/base.rs:75:23                                              
   |                                                       
75 |     gr_name:   *const c_char,         // group name
   |                       ^^^^^^ undefined or not in scope
...

error[E0412]: type name `c_passwd` is undefined or not in scope
  --> src/base.rs:82:39
   |
82 |     fn getpwuid(uid: uid_t) -> *const c_passwd;
   |                                       ^^^^^^^^ undefined or not in scope
...
error[E0412]: type name `os::UserExtras` is undefined or not in scope
   --> src/base.rs:105:13                                  
    |                                                   
105 |     extras: os::UserExtras,                          
    |             ^^^^^^^^^^^^^^ undefined or not in scope    
...
error[E0412]: type name `os::GroupExtras` is undefined or not in scope
   --> src/base.rs:165:13  
    |                              
165 |     extras: os::GroupExtras,
    |             ^^^^^^^^^^^^^^^ undefined or not in scope  

error[E0433]: failed to resolve. Could not find `UserExtras` in `os`
   --> src/base.rs:247:28
    |                                                             
247 |             extras:        os::UserExtras::from_passwd(passwd),                      
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `UserExtras` in `os`

```
This is with rustc 1.15.1. Yay manual os whitelisting in base.rs...... :/

**Comment by lilydjwg** [comment]
Same here with rustc 1.16.0.

**Comment by ltratt** [comment]
@wezm fixed the OpenBSD problems in https://github.com/ogham/rust-users/pull/13 and I've confirmed they still work well with the new OpenBSD Rust 1.19 port. Hopefully @ogham will be able to merge this and make a new release soon for those of us on OpenBSD!

**Comment by ogham** [comment]
Released as 0.5.3. Sorry it took so long.

**Comment by ltratt** [comment]
Thanks!
